# Generated by Django 3.0.5 on 2021-04-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoggerFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='ip address')),
                ('additional_ip_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='additional ip address info')),
                ('date', models.DateTimeField()),
                ('method', models.CharField(max_length=10, verbose_name='http method')),
                ('uri', models.CharField(max_length=300, verbose_name='uri')),
                ('http_version', models.CharField(max_length=10, verbose_name='http version')),
                ('status', models.PositiveIntegerField(verbose_name='status code')),
                ('body_length', models.PositiveIntegerField(default=0, verbose_name='body length')),
                ('referer_from', models.URLField(blank=True, null=True, verbose_name='referer')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='user-agent')),
            ],
            options={
                'verbose_name': 'Logger File',
                'verbose_name_plural': 'Logger Files',
                'ordering': ('-date',),
            },
        ),
    ]
